repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: system
        always_run: true
        pass_filenames: false
      - id: ruff-check
        name: ruff check --fix
        entry: ruff check --fix
        language: system
        always_run: true
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: mypy server/
        language: system
        always_run: true
        pass_filenames: false
      - id: pytest
        name: pytest -x
        entry: pytest -x server/tests/
        language: system
        always_run: true
        pass_filenames: false
